### ISSUE TITLE
Re-drawing bricks on canvas after game win

### ISSUE THREAD

**Issue by IgorDraskovic** [IgorDraskovic/Igor-s-Crappy-Game#1]
I am trying to redraw my bricks after I win the game.  Thus far I have managed to redraw the paddle and ball, but only one of the bricks!  

This issue is somewhere in this segment of code...I think.

Thanks in advance!

function collisionDetection() {
  for(c=0; c<brickColumnCount; c++) {
    for(r=0; r<brickRowCount; r++) {
      var b = bricks[c][r];
      if(b.status == 1) {
      if(x > b.x && x < b.x+brickWidth && y > b.y && y < b.y+brickHeight) {
                dy = -dy;
                b.status = 0;
                score ++;
                if(score == brickRowCount*brickColumnCount) {
                  alert("You Win!");
                  //this only re-draws one brick!!!
                  b.status = 1;
                  x = canvas.width/2;
                  y = canvas.height-30;
                  dx = 2;
                  dy = -2;
                  paddleX = (canvas.width-paddleWidth)/2;
          }
        }
      }
    }
  }
}

setInterval(draw, 10);

**Comment by ajhofferber** [comment]
Hey Igor! Do you want to pair on this? Or did someone already meet with you?

**Comment by IgorDraskovic** [comment]
No one yet!  Where can I find you!

**Comment by ajhofferber** [comment]
2nd floor lobby! i am sitting across from terrell, but am grabbing some tea!
