### ISSUE TITLE
Project One Feedback

### ISSUE THREAD

**Issue by ajhofferber** [IgorDraskovic/Igor-s-Crappy-Game#2]
Hey Igor,

Nice work on your project! It works really well and is fun to play. Also, props for checking out Canvas and exploring the things you can use it for.

I know there are a lot of tutorials out there for similar games, and although it's never a bad idea to look around and gain inspiration from the way other people approach things, especially when trying out something like Canvas, we just want to make sure that you are working through this stuff on your own too! I know that you mentioned referencing some tutorials, but I would love to understand which parts of your code were inspired by tutorials and which parts of it you worked through and generated independently. If you were to have like 2 more days on the project, what kinds of things would you add? How would you go about adding in additional features? What about maybe a button to start the game instead of having it start on load? Or possibly the addition of blocks that require multiple hits to destroy?

Again, not saying you shouldn't explore other code, we just want to make sure that you all were wrestling with the right kind of logic work for this project. But overall, I really like what you were able to present as your project and can't wait to see what ideas you have for future versions of it!

-Ash

**Comment by Avizacherman** [comment]
Igor,

Overall I think your game works great. I would agree with Ash's sentiments. I know there are versions of breakout where you get powerups. How do you think you would implement these into your game? 

Keep working and it will all come to you. 

Score: 2 (Refer to project markdown for the rubric)

**Comment by IgorDraskovic** [comment]
Hi guys I really appreciate the feedback.  I remember obtaining bits and peaces from tutorials and then making some canvas modifications and playing with the dimensions, speed and colision of the objects.  I could not write the complex collision function on my own unfortunately.  
I would still like to figure out how to increment the ball as I advance in levels and I would like to populate the canvas with more and different brick patterns.  Unfortunately I am barley keeping up with the homework as it is, and do not really have had no time to work on the project…

Regards,

Igor
